Remove master branch publish check (#319)

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -14,9 +14,11 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Fail if we are attempting to run on the master branch
-      if: ${{GITHUB.REF_NAME == 'master'}} && github.repository == 'space-wizards/space-station-14'
-      run: exit 1
+    # Moffstation - Start - Remove Upstream specific check - "FORKS REMOVE THIS" https://github.com/space-wizards/space-station-14/pull/38431
+#    - name: Fail if we are attempting to run on the master branch
+#      if: GITHUB.REF_NAME == 'master' && github.repository == 'space-wizards/space-station-14'
+#      run: exit 1
+    # Moffstation - End
 
     - name: Install dependencies
       run: sudo apt-get install -y python3-paramiko python3-lxml
